### ISSUE TITLE
Why sign google CLA for contributing ?

### ISSUE THREAD

**Issue by kishaningithub** [luci/go-render#2]
The first point in the [contributing section in readme](https://github.com/luci/go-render#contributing) says "Sign the Google CLA"

Also the first point in the same readme says "This is not an official Google product."

Why sign Google CLA when it is not a google product ?

**Comment by riannucci** [comment]
Even though the project is not an official Google project (i.e. it does not have Google's branding or any sort of official endorsement), it is still owned by Google, and so the CLA is still required to contribute code to it.

Does that help?

**Comment by kishaningithub** [comment]
@riannucci I dint know it was owned by google. Thanks for that info. I guess a readme update would help people having same doubts. Since this is documented here in github issues i am closing this.
